# Generated by Django 5.2.9 on 2025-12-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Stu_aadhar',
            field=models.IntegerField(),
        ),
    ]
