# Generated by Django 5.2.9 on 2025-12-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=40)),
                ('Stu_email', models.EmailField(max_length=254)),
                ('Stu_contact', models.IntegerField()),
                ('Stu_aadhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aadhar', to='app.aadhar')),
            ],
        ),
    ]
